<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { trpc } from '../lib/trpc'
import LoadingSpinner from './ui/LoadingSpinner.vue'

type Plan = { id:string; name:string; direction:'push'|'pull'; source:string; destination:string; remoteHost:string|null; remoteUser:string|null; remotePort:number; sshKeyPath:string|null; schedule:'manual'|'hourly'|'daily'|'weekly'; scheduleHour:number; scheduleMinute:number; scheduleWeekday:number; deleteExtra:boolean; compress:boolean; bandwidthLimit:number|null; excludes:string[]; enabled:boolean; lastStatus:string|null; lastRunAt:string|null; lastError:string|null; nextRunAt:string|null }
type PlanForm = Omit<Plan, 'id'|'lastStatus'|'lastRunAt'|'lastError'|'nextRunAt'>
const empty = ():PlanForm => ({ name:'', direction:'push', source:'', destination:'', remoteHost:null, remoteUser:null, remotePort:22, sshKeyPath:null, schedule:'manual', scheduleHour:2, scheduleMinute:0, scheduleWeekday:0, deleteExtra:false, compress:true, bandwidthLimit:null, excludes:[], enabled:true })
const plans=ref<Plan[]>([]), loading=ref(true), saving=ref(false), adding=ref(false), error=ref(''), remote=ref(false), excludeText=ref('')
const form=ref(empty())
let poll:number|undefined
const hasRunning=computed(()=>plans.value.some(p=>['pending','running'].includes(p.lastStatus??'')))
const fmt=(v:string|null)=>v?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—'
async function load(){ plans.value=await trpc.backup.list.query() as Plan[] }
async function save(){ error.value=''; saving.value=true; try { await trpc.backup.create.mutate({...form.value, remoteHost:remote.value?form.value.remoteHost:null, remoteUser:remote.value?form.value.remoteUser:null, sshKeyPath:remote.value?form.value.sshKeyPath:null, excludes:excludeText.value.split('\n').map(x=>x.trim()).filter(Boolean)}); form.value=empty(); excludeText.value=''; remote.value=false; adding.value=false; await load() } catch(e:any){error.value=e?.message??'Failed to create backup'} finally{saving.value=false} }
async function run(id:string){ error.value=''; try{await trpc.backup.run.mutate({id}); await load()}catch(e:any){error.value=e?.message??'Failed to start backup'} }
async function remove(id:string){if(!confirm('Delete this backup plan? Existing backup files will not be removed.'))return; await trpc.backup.delete.mutate({id}); await load()}
onMounted(async()=>{try{await load()}finally{loading.value=false}; poll=window.setInterval(()=>{if(hasRunning.value)void load()},3000)})
onUnmounted(()=>{if(poll)clearInterval(poll)})
</script>

<template><section class="space-y-4">
  <div class="flex flex-col items-start justify-between gap-3 sm:flex-row sm:gap-4"><div><h2 class="text-base font-semibold text-[var(--c-text-1)]">Data backups</h2><p class="mt-1 max-w-lg text-xs leading-relaxed text-[var(--c-text-3)]">Copy NAS data to another folder or SSH host, or pull a remote target onto this NAS. Transfers use rsync and SSH keys; passwords are never stored.</p></div><button v-if="!adding" class="btn btn-primary btn-xs" @click="adding=true">New plan</button></div>
  <div v-if="error" class="rounded-lg border border-[var(--c-danger)]/30 bg-[var(--c-danger)]/10 px-3 py-2 text-xs text-[var(--c-danger)]">{{error}}</div>
  <form v-if="adding" class="space-y-4 rounded-xl border border-[var(--c-border-strong)] bg-[var(--c-surface)] p-4" @submit.prevent="save">
    <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-[var(--c-text-2)]">Plan name<input v-model="form.name" required maxlength="80" class="ui-input mt-1" placeholder="Nightly media backup"></label><label class="text-xs text-[var(--c-text-2)]">Transfer direction<select v-model="form.direction" class="ui-input mt-1"><option value="push">NAS → destination</option><option value="pull">Target → NAS</option></select></label></div>
    <label class="flex items-center gap-2 text-xs text-[var(--c-text-2)]"><input v-model="remote" type="checkbox"> Use a remote SSH target</label>
    <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-[var(--c-text-2)]">{{form.direction==='push'?'NAS source':'Target source'}}<input v-model="form.source" required class="ui-input mt-1 font-mono" placeholder="/mnt/data"></label><label class="text-xs text-[var(--c-text-2)]">{{form.direction==='push'?'Destination':'NAS destination'}}<input v-model="form.destination" required class="ui-input mt-1 font-mono" placeholder="/mnt/backup"></label></div>
    <div v-if="remote" class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-[var(--c-text-2)]">Host<input v-model="form.remoteHost" required class="ui-input mt-1" placeholder="backup.example.net"></label><label class="text-xs text-[var(--c-text-2)]">SSH user<input v-model="form.remoteUser" required class="ui-input mt-1" placeholder="backup"></label><label class="text-xs text-[var(--c-text-2)]">SSH key path<input v-model="form.sshKeyPath" required class="ui-input mt-1 font-mono" placeholder="/root/.ssh/hsi_backup"></label><label class="text-xs text-[var(--c-text-2)]">Port<input v-model.number="form.remotePort" type="number" min="1" max="65535" class="ui-input mt-1"></label><p class="sm:col-span-2 text-[11px] text-[var(--c-text-3)]">The host must already exist in root's known_hosts and the private key must be mode 0600 or stricter.</p></div>
    <div class="grid gap-3 sm:grid-cols-3"><label class="text-xs text-[var(--c-text-2)]">Schedule<select v-model="form.schedule" class="ui-input mt-1"><option value="manual">Manual only</option><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><label v-if="form.schedule!=='manual'" class="text-xs text-[var(--c-text-2)]">Minute<input v-model.number="form.scheduleMinute" type="number" min="0" max="59" class="ui-input mt-1"></label><label v-if="['daily','weekly'].includes(form.schedule)" class="text-xs text-[var(--c-text-2)]">Hour<input v-model.number="form.scheduleHour" type="number" min="0" max="23" class="ui-input mt-1"></label><label v-if="form.schedule==='weekly'" class="text-xs text-[var(--c-text-2)]">Day<select v-model.number="form.scheduleWeekday" class="ui-input mt-1"><option v-for="(d,i) in ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']" :key="d" :value="i">{{d}}</option></select></label></div>
    <label class="block text-xs text-[var(--c-text-2)]">Exclusions, one pattern per line<textarea v-model="excludeText" rows="3" class="ui-input mt-1 font-mono" placeholder=".cache/&#10;*.tmp"></textarea></label>
    <div class="flex flex-wrap gap-4 text-xs text-[var(--c-text-2)]"><label class="flex items-center gap-2"><input v-model="form.compress" type="checkbox"> Compress transfer</label><label class="flex items-center gap-2"><input v-model="form.deleteExtra" type="checkbox"> Mirror deletions at destination</label></div>
    <p v-if="form.deleteExtra" class="rounded-lg bg-amber-500/10 px-3 py-2 text-xs text-amber-600">Mirror mode deletes destination files that no longer exist at the source. Verify both paths before enabling it.</p>
    <div class="flex gap-2"><button class="btn btn-primary btn-sm" :disabled="saving"><LoadingSpinner v-if="saving" class="h-3.5 w-3.5"/>{{saving?'Saving…':'Save plan'}}</button><button type="button" class="btn btn-ghost btn-sm" @click="adding=false">Cancel</button></div>
  </form>
  <div v-if="loading" class="text-sm text-[var(--c-text-3)]">Loading…</div><div v-else-if="!plans.length&&!adding" class="rounded-xl border border-dashed border-[var(--c-border-strong)] p-8 text-center text-sm text-[var(--c-text-3)]">No data backup plan yet.</div>
  <article v-for="p in plans" :key="p.id" class="rounded-xl border border-[var(--c-border)] bg-[var(--c-surface)] p-4"><div class="flex min-w-0 flex-col items-start justify-between gap-3 sm:flex-row"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="text-sm font-medium text-[var(--c-text-1)]">{{p.name}}</h3><span class="rounded-full bg-[var(--c-surface-alt)] px-2 py-0.5 text-[10px] uppercase text-[var(--c-text-3)]">{{p.schedule}}</span></div><p class="mt-1 break-all font-mono text-[11px] text-[var(--c-text-3)]">{{p.remoteHost&&p.direction==='pull'?`${p.remoteUser}@${p.remoteHost}:`:''}}{{p.source}} → {{p.remoteHost&&p.direction==='push'?`${p.remoteUser}@${p.remoteHost}:`:''}}{{p.destination}}</p></div><div class="flex shrink-0 gap-2"><button class="btn btn-primary btn-xs" :disabled="['pending','running'].includes(p.lastStatus??'')" @click="run(p.id)"><LoadingSpinner v-if="['pending','running'].includes(p.lastStatus??'')" class="h-3 w-3"/>{{['pending','running'].includes(p.lastStatus??'')?'Running':'Run now'}}</button><button class="btn btn-ghost btn-xs" @click="remove(p.id)">Delete</button></div></div><div class="mt-3 grid gap-2 text-[11px] text-[var(--c-text-3)] sm:grid-cols-3"><span>Status: <b class="text-[var(--c-text-2)]">{{p.lastStatus??'Never run'}}</b></span><span>Last run: {{fmt(p.lastRunAt)}}</span><span>Next run: {{fmt(p.nextRunAt)}}</span></div><p v-if="p.lastError" class="mt-2 break-words text-xs text-[var(--c-danger)]">{{p.lastError}}</p></article>
</section></template>
